### PR TITLE
CI test

### PR DESCRIPTION
**Pull request by Sjors**
This tests CI for a pull request on a fork against a branch that's not master.

Demo for https://github.com/bitcoin/bitcoin/pull/29274

### CODE REVIEW

**Comment by Sjors** [comment]
Not sure how to get the USDT runner working, but at least that seems doable in theory.

@maflcko the error `Failed to compile BPF module` is a bit cryptic.
https://cirrus-ci.com/task/5275704273666048?logs=ci#L3276

I have `bpfcc-tools linux-headers-$(uname --kernel-release)` installed on the machine, but I guess it's missing something else.

**Comment by Sjors** [comment]
Sounds like it, but it seems better if this test is skipped if it's missing a permission. The CI machine is still doing enough other useful stuff.

**Comment by Sjors** [comment]
> move the task to GHA

That could work too.

**Comment by m3dwards** [comment]
> @m3dwards is working on this

Still a WIP but here is draft PR: https://github.com/bitcoin/bitcoin/pull/30193

**Comment by 0xB10C** [comment]
> Not sure how to get the USDT runner working, but at least that seems doable in theory.
> 
> @maflcko the error `Failed to compile BPF module` is a bit cryptic.
> https://cirrus-ci.com/task/5275704273666048?logs=ci#L3276
> 
> I have `bpfcc-tools linux-headers-$(uname --kernel-release)` installed on the machine, but I guess it's missing something else. The check that skips this test doesn't catch it.

It should check for permissions beforehand and otherwise skip the USDT tests, no?

https://github.com/bitcoin/bitcoin/blob/f61ede574c12f1f8ae67f38f15387586719c856f/test/functional/interface_usdt_mempool.py#L135

**Comment by Sjors** [comment]
https://github.com/bitcoin/bitcoin/pull/30193 landed.

Currently trying if `qemu-aarch64` is quick enough, see https://github.com/bitcoin/bitcoin/pull/29274#discussion_r1644154081

**Pull request closed without merging**
