### PR TITLE
rpc: checkblock, add checkBlock() to Mining interface

### PR DESCRIPTION
**Pull request by Sjors**
RPC and IPC for checking weak blocks (reduced proof of work) and block templates (no proof of work) against all consensus rules.

Uses the first test commit from #31283 to refactor `miner_tests.cpp`.

### CODE REVIEW

**Comment by plebhash** [comment]
this can be useful for Sv2 JDS to check template validity

cc @gitgab19

**Comment by Sjors** [comment]
Simplified things by just calling `ConnectBlock` instead of copy-pasting it.

**Comment by Sjors** [comment]
Also added `checkBlock()` to the Mining interface. If the JDS can speak [cap&proto](https://capnproto.org) this should be more performant than using the RPC. Though it's probably not a huge difference.

**Comment by Sjors** [comment]
I got rid of `StateCatcher` indirection. With a little bit more cleanup I can probably open a PR to the main repo.

**Comment by Sjors** [comment]
Moving to #31564.

**Pull request closed without merging**
